version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    ports:
      - "5555:5555"
    networks:
      - backend
    depends_on:
      - database

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - server

networks:
  backend:

volumes:
  db_init:
  db_data: