version: '3'

services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "5555:5555"
    networks:
      - app
    depends_on:
      - database

  client:
    build: ./client
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - server

volumes:
  db_init:
  db_data:

networks:
  app:
