version: '3'

name: cowsay

services:
  database:
    container_name: database
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  server:
    container_name: server
    build: ./server
    ports:
      - "5555:5555"
    networks:
      - frontend
      - backend
    depends_on:
      - database

  client:
    container_name: client
    build: ./client
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - server

volumes:
  db_init:
  db_data:

networks:
  frontend:
  backend:
