global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['server:5555']

  - job_name: 'client'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
