{
 "title": "WebServiceOverview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Database Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"movielens-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active DB Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"movielens-postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Total Records Returned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{instance=\"movielens-postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask Requests in 15 seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "sum by(method, job, instance) (flask_http_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask Total Request Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "sum by(instance, method, path, status) (flask_http_request_duration_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"client\", instance=\"nginx-prometheus-exporter:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Nginx connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 10 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Total Num Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Personality DB Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"personality-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Personality DB Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"personality-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Personality DB Total Records Returned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"personality\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Total Incoming Commands",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "redis_commands_processed_total{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"redis-exporter:9121\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}